[git]
commit_parsers = [
  { message = "^feat", group = "<!-- 0 -->ğŸš€ Features", scope = "form" },
  { message = "^fix", group = "<!-- 1 -->ğŸ› Bug Fixes", scope = "form" },
  { message = "^doc", group = "<!-- 3 -->ğŸ“š Documentation", scope = "form" },
  { message = "^perf", group = "<!-- 4 -->âš¡ Performance", scope = "form" },
  { message = "^refactor", group = "<!-- 2 -->ğŸšœ Refactor", scope = "form" },
  { message = "^style", group = "<!-- 5 -->ğŸ¨ Styling", scope = "form" },
  { message = "^test", group = "<!-- 6 -->ğŸ§ª Testing", scope = "form" },
  { message = "^chore\\(release\\): prepare for", skip = true, scope = "form" },
  { message = "^chore\\(deps.*\\)", skip = true, scope = "form" },
  { message = "^chore\\(pr\\)", skip = true, scope = "form" },
  { message = "^chore\\(pull\\)", skip = true, scope = "form" },
  { message = "^chore|^ci", group = "<!-- 7 -->âš™ï¸ Miscellaneous Tasks", scope = "form" },
  { body = ".*security", group = "<!-- 8 -->ğŸ›¡ï¸ Security", scope = "form" },
  { message = "^revert", group = "<!-- 9 -->â—€ï¸ Revert", scope = "form" },
  { message = ".*", group = "<!-- 10 -->ğŸ’¼ Other", scope = "form" },
]
